osx_image: xcode10.2
language: objective-c
sudo: required

env:
  global:
    - PROJECT="SCUIBuildKit.xcodeproj"
    - SCHEME="SCUIBuildKit"
    - IOS_SDK="iphonesimulator12.2"
    - DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=12.2"
    - FRAMEWORK="SCUIBuildKit"
    - CODE_COV_TOKEN="c826c35f-6230-414e-b819-d8b61a733bba"

install:
  - swift --version

before_script:
  - gem install xcpretty -N
  - gem install xcpretty-travis-formatter
  - gem install cocoapods
  - pod repo update
  - pod update
  - brew install swiftlint

script:
  - set -o pipefail
  - xcodebuild clean build test
    -prject "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$IOS_SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash) -j SCUIBuildKit --cover-xml
