osx_image: xcode10.2
language: objective-c
sudo: required

env:
  global:
    - PROJECT="SCUIBuildKit.xcworkspace"
    - SCHEME="SCUIBuildKit"
    - IOS_SDK="iphonesimulator12.2"
    - DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=12.2"
    - FRAMEWORK="SCUIBuildKit"
    - CODE_COV_TOKEN="f8383c60-a11f-4ead-a040-45a8d57bae04"

install:
  - swift --version

before_script:
  - gem install xcpretty -N
  - gem install xcpretty-travis-formatter
  - brew install swiftlint

script:
  - set -o pipefail
  - xcodebuild clean build test
    -workspace "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$IOS_SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f8383c60-a11f-4ead-a040-45a8d57bae04 --cover-xml

notifications:
  slack: interactord:Z4o1u31lio6owH5ic2qWuSGo
  on_success: always
