codecov:
  notify:
    require_ci_to_pass: yes
comment:
  layout: "header, changes, diff, sunburst"

coverage:
  ignore:
  - .*Tests.swift
  - .*Spec.swift
  - .Stub*.swift
  - .*Mock.swift
  
  status:
    patch: false